[configurationNetwork]
seed = [6, 7, 8, 9, 10]                 # 5
# probability of LoRa device on edge
gamma = [0.0, 0.33, 0.66, 1.0]          # 4
# probability of device on smartphone
beta = [0.0, 0.33, 0.66, 1.0]           # 4
dee = [0.1, 1.0, 10.0]                  # 3
dcc = [5, 25, 100]                      # 3
dec = [10, 50, 300, 1000]               # 4
dscnd = [50, 150, 500]                  # 3
dlocalhost = 0.015

[brokerHostConfig]
type = ["CLOUD", "EDGE"]                # 2
dataRate = 1e9

[[hostsConfig]]
    type = "CLOUD"
    id = "c000"
[[hostsConfig]]
    type = "EDGE"
    dataRate = 10
